/********************************************************************
	created:	2009/02/17
	created:	17:2:2009   8:14
	filename: 	x:\ProjectRoot\svn\local\vtPhysX\SDK\include\core\Common\vtParameterSubItemIdentifiers_Joints.h
	file path:	x:\ProjectRoot\svn\local\vtPhysX\SDK\include\core\Common 
	file base:	vtParameterSubItemIdentifiers_Joints
	file ext:	h
	author:		Günter Baumgart
	
	purpose:	Joint parameter items for custom structures. 
*********************************************************************/
#ifndef __VTPARAMETERSUBITEMIDENTIFIERS_JOINTS_H__
#define __VTPARAMETERSUBITEMIDENTIFIERS_JOINTS_H__
 
enum PS_JPOINT_ON_LINE_MEMBERS
{
	PS_JPOL_BODY_B,
	PS_JPOL_ANCHOR,
	PS_JPOL_ANCHOR_REF,

	PS_JPOL_AXIS,
	PS_JPOL_AXIS_REF,
	PS_JPOL_COLLISION,

	PS_JPOL_MAX_FORCE,
	PS_JPOL_MAX_TORQUE,
};

enum PS_JPOINT_IN_PLANE_MEMBERS
{
	PS_JPIP_BODY_B,
	PS_JPIP_ANCHOR,
	PS_JPIP_ANCHOR_REF,

	PS_JPIP_AXIS,
	PS_JPIP_AXIS_REF,
	PS_JPIP_COLLISION,

	PS_JPIP_MAX_FORCE,
	PS_JPIP_MAX_TORQUE,
};

enum PS_JREVOLUTE
{

	PS_JREVOLUTE_BODY_B,
	PS_JREVOLUTE_ANCHOR,
	PS_JREVOLUTE_ANCHOR_REF,

	PS_JREVOLUTE_AXIS,
	PS_JREVOLUTE_AXIS_REF,
	PS_JREVOLUTE_COLLISION,

	PS_JREVOLUTE_PROJ_MODE,
	PS_JREVOLUTE_PROJ_DISTANCE,
	PS_JREVOLUTE_PROJ_ANGLE,
    
	PS_JREVOLUTE_SPRING,
	PS_JREVOLUTE_LIMIT_HIGH,
	PS_JREVOLUTE_LIMIT_LOW,
	PS_JREVOLUTE_MOTOR,

	PS_JREVOLUTE_MAX_FORCE,
	PS_JREVOLUTE_MAX_TORQUE,

};
enum PS_JCYLINDRICAL_MEMBERS
{
	
	PS_JCYLINDRICAL_BODY_B,
	PS_JCYLINDRICAL_ANCHOR,
	PS_JCYLINDRICAL_ANCHOR_REF,

	PS_JCYLINDRICAL_AXIS,
	PS_JCYLINDRICAL_AXIS_REF,
	PS_JCYLINDRICAL_COLLISION,

	PS_JCYLINDRICAL_MAX_FORCE,
	PS_JCYLINDRICAL_MAX_TORQUE,


};
enum PS_JPRISMATIC_MEMBERS
{
	PS_JPRISMATIC_BODY_B,
	PS_JPRISMATIC_ANCHOR,
	PS_JPRISMATIC_ANCHOR_REF,

	PS_JPRISMATIC_AXIS,
	PS_JPRISMATIC_AXIS_REF,
	PS_JPRISMATIC_COLLISION,
	PS_JPRISMATIC_MAX_FORCE,
	PS_JPRISMATIC_MAX_TORQUE,
};
enum PS_JBALL_MEMBERS
{
	PS_JBALL_BODY_B,
	PS_JBALL_ANCHOR,
	PS_JBALL_ANCHOR_REF,
	PS_JBALL_GLOBAL_AXIS,
	PS_JBALL_GLOBAL_AXIS_REF,
	PS_JBALL_LIMIT_SWING_AXIS,
	PS_JBALL_PROJ_MODE,
	PS_JBALL_PROJ_DISTANCE,
	PS_JBALL_COLLISION,
	PS_JBALL_SWING_LIMIT,
	PS_JBALL_TWIST_HIGH,
	PS_JBALL_TWIST_LOW,
	PS_JBALL_SWING_SPRING,
	PS_JBALL_TWIST_SPRING,
	PS_JBALL_JOINT_SPRING,

	PS_JBALL_MAX_FORCE,
	PS_JBALL_MAX_TORQUE,


};

enum PS_JFIXED_MEMBERS
{
	PS_JFIXED_BODY_B,
	PS_JFIXED_MAX_FORCE,
	PS_JFIXED_MAX_TORQUE,
};
enum PS_JDISTANCE_MEMBERS
{
	PS_JDISTANCE_BODY_B,
	PS_JDISTANCE_LOCAL_ANCHOR_A_POS,
	PS_JDISTANCE_LOCAL_ANCHOR_A_REF,

	PS_JDISTANCE_LOCAL_ANCHOR_B_POS,
	PS_JDISTANCE_LOCAL_ANCHOR_B_REF,

	PS_JDISTANCE_COLL,
	PS_JDISTANCE_MIN_DISTANCE,
	PS_JDISTANCE_MAX_DISTANCE,
	PS_JDISTANCE_SPRING,

	PS_JDISTANCE_MAX_FORCE,
	PS_JDISTANCE_MAX_TORQUE,
};

enum PS_JLIMIT_PLANE_MEMBERS
{
	PS_JLP_BODY_B_REF,
	PS_JLP_JOINT_TYPE,
	PS_JLP_RESTITUTION,
	PS_JLP_IS_ON_BODY_B,
	PS_JLP_LIMIT_POINT,
	PS_JLP_LIMIT_POINT_REF,
	PS_JLP_NORMAL,
	PS_JLP_NORMAL_REF,
	PS_JLP_PT_IN_PLANE,
	PS_JLP_PT_IN_PLANE_REF,
};

enum PS_D6_AXIS_ITEM
{
	PS_D6_AXIS_ITEM_MODE,
	PS_D6_AXIS_ITEM_LIMIT,
};

enum PS_D6
{
	PS_JD6_BODY_B,
	PS_JD6_ANCHOR,
	PS_JD6_ANCHOR_REF,

	PS_JD6_AXIS,
	PS_JD6_AXIS_REF,

	PS_JD6_AXIS_MASK,

	PS_JD6_X,
	PS_JD6_Y,
	PS_JD6_Z,
	PS_JD6_TWIST_SWING1,
	PS_JD6_TWIST_SWING2,
	PS_JD6_TWIST_LOW,
	PS_JD6_TWIST_HIGH,
};
#endif