#ifndef __VEHICLE_AND_WHEEL_STRUCTS_H__
#define __VEHICLE_AND_WHEEL_STRUCTS_H__
/*
typedef enum PS_WHEELSHAPE
{
	E_WD_XML,
	E_WD_SUSPENSION,
	E_WD_SPRING_RES,
	E_WD_DAMP,
	E_WD_SPRING_BIAS,
	E_WD_MAX_BFORCE,
	E_WD_FSIDE,
	E_WD_FFRONT,
	E_WD_APPROX,
	E_WD_FLAGS,
	E_WD_SFLAGS,
	E_WD_LAT_FUNC,
	E_WD_LONG_FUNC,
};
*/

#endif