/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class vtWindow : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal vtWindow(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(vtWindow obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~vtWindow() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csWindowPINVOKE.delete_vtWindow(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public vtWindow() : this(csWindowPINVOKE.new_vtWindow(), true) {
  }

  public int CreateAsChild(SWIGTYPE_p_long parent) {
    int ret = csWindowPINVOKE.vtWindow_CreateAsChild(swigCPtr, SWIGTYPE_p_long.getCPtr(parent));
    return ret;
  }

  public int Run() {
    int ret = csWindowPINVOKE.vtWindow_Run(swigCPtr);
    return ret;
  }

  public int Init() {
    int ret = csWindowPINVOKE.vtWindow_Init(swigCPtr);
    return ret;
  }

  public void ParseCommandLine(string cmdLine) {
    csWindowPINVOKE.vtWindow_ParseCommandLine(swigCPtr, cmdLine);
  }

  public void Destroy() {
    csWindowPINVOKE.vtWindow_Destroy(swigCPtr);
  }

  public int Tick() {
    int ret = csWindowPINVOKE.vtWindow_Tick(swigCPtr);
    return ret;
  }

  public int DoFrame() {
    int ret = csWindowPINVOKE.vtWindow_DoFrame(swigCPtr);
    return ret;
  }

  public int Show(int ShowFlags) {
    int ret = csWindowPINVOKE.vtWindow_Show(swigCPtr, ShowFlags);
    return ret;
  }

  public int GetWidth() {
    int ret = csWindowPINVOKE.vtWindow_GetWidth(swigCPtr);
    return ret;
  }

  public int GetHeight() {
    int ret = csWindowPINVOKE.vtWindow_GetHeight(swigCPtr);
    return ret;
  }

  public int UpdateRenderSize(int w, int h) {
    int ret = csWindowPINVOKE.vtWindow_UpdateRenderSize(swigCPtr, w, h);
    return ret;
  }

  public int SendMessage(string targetObject, string message, int id0, int id1, int id2, int value) {
    int ret = csWindowPINVOKE.vtWindow_SendMessage__SWIG_0(swigCPtr, targetObject, message, id0, id1, id2, value);
    return ret;
  }

  public int SendMessage(string targetObject, string message, int id0, int id1, int id2, float value) {
    int ret = csWindowPINVOKE.vtWindow_SendMessage__SWIG_1(swigCPtr, targetObject, message, id0, id1, id2, value);
    return ret;
  }

  public int SendMessage(string targetObject, string message, int id0, int id1, int id2, string value) {
    int ret = csWindowPINVOKE.vtWindow_SendMessage__SWIG_2(swigCPtr, targetObject, message, id0, id1, id2, value);
    return ret;
  }

  public int HasMessages() {
    int ret = csWindowPINVOKE.vtWindow_HasMessages(swigCPtr);
    return ret;
  }

  public int GetNumMessages() {
    int ret = csWindowPINVOKE.vtWindow_GetNumMessages(swigCPtr);
    return ret;
  }

  public string GetMessageName(int messageID) {
    string ret = csWindowPINVOKE.vtWindow_GetMessageName(swigCPtr, messageID);
    return ret;
  }

  public int GetNumParameters(int messageID) {
    int ret = csWindowPINVOKE.vtWindow_GetNumParameters(swigCPtr, messageID);
    return ret;
  }

  public int GetMessageParameterType(int messageID, int parameterSubID) {
    int ret = csWindowPINVOKE.vtWindow_GetMessageParameterType(swigCPtr, messageID, parameterSubID);
    return ret;
  }

  public int GetMessageValueInt(int messageID, int parameterSubID) {
    int ret = csWindowPINVOKE.vtWindow_GetMessageValueInt(swigCPtr, messageID, parameterSubID);
    return ret;
  }

  public float GetMessageValueFloat(int messageID, int parameterSubID) {
    float ret = csWindowPINVOKE.vtWindow_GetMessageValueFloat(swigCPtr, messageID, parameterSubID);
    return ret;
  }

  public string GetMessageValueStr(int messageID, int parameterSubID) {
    string ret = csWindowPINVOKE.vtWindow_GetMessageValueStr(swigCPtr, messageID, parameterSubID);
    return ret;
  }

  public void CleanMessages() {
    csWindowPINVOKE.vtWindow_CleanMessages(swigCPtr);
  }

  public void DeleteMessage(int messageID) {
    csWindowPINVOKE.vtWindow_DeleteMessage(swigCPtr, messageID);
  }

  public void Pause() {
    csWindowPINVOKE.vtWindow_Pause(swigCPtr);
  }

  public void Play() {
    csWindowPINVOKE.vtWindow_Play(swigCPtr);
  }

  public void LoadCompostion(string file) {
    csWindowPINVOKE.vtWindow_LoadCompostion(swigCPtr, file);
  }

  public void Terminate(int flags) {
    csWindowPINVOKE.vtWindow_Terminate(swigCPtr, flags);
  }

  public int WndProc(SWIGTYPE_p_long hWnd, int uMsg, SWIGTYPE_p_long wParam, SWIGTYPE_p_long lParam) {
    int ret = csWindowPINVOKE.vtWindow_WndProc(swigCPtr, SWIGTYPE_p_long.getCPtr(hWnd), uMsg, SWIGTYPE_p_long.getCPtr(wParam), SWIGTYPE_p_long.getCPtr(lParam));
    return ret;
  }

}
